backend:
  name: git-gateway
  branch: main
site_url: https://netlify.app
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "listings"
    label: "Active Listings"
    folder: "src/content/listings"
    create: true
    fields:
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["Active", "In Contract"],
        }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - label: "Gallery Images"
        name: "gallery"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "closed"
    label: "Recently Sold"
    folder: "src/content/closed"
    create: true
    fields:
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Sale Price", name: "salePrice", widget: "string" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - label: "Gallery Images"
        name: "gallery"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
